[package]
name = "findutils-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fts = "0.3"
getopt = "1.1"
enum-iterator = "2"
downcast-rs = "1.2.1"

[[bin]]
name = "find"
